spring:
  thymeleaf:
    cache: false
    check-template-location: true
    mode: HTML
    prefix: classpath:templates/
    suffix: .html
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      platform: local

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 클라이언트아이디
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

app:
  auth:
    tokenSecret: D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 1800000
    refreshTokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect

logging:
  config: classpath:logback.xml
  level:
    org:
      hibernate:
        type: trace
    root: warn
    com.example.batch.demo: debug
    org.hibernate.type.descriptor.sql: debug