POST http://localhost:8080/auth/login
Content-Type: application/json

{"test": "test"}

###

POST http://localhost:8080/auth/signup
Content-Type: application/json

{"test": "test"}

###

GET http://localhost:8080/test

